export interface Vanity3DPreviewProps {
  width: number;
  height: number;
  depth: number;
  brand: string;
  finish: string;
  doorStyle: string;
  numDrawers: number;
  handleStyle: string;
  cabinetPosition?: string;
  fullscreen?: boolean;
  includeRoom?: boolean;
  roomLength?: number;
  roomWidth?: number;
  roomHeight?: number;
  floorType?: string;
  tileColor?: string;
  woodFloorFinish?: string;
  includeWalls?: boolean;
  hasWindow?: boolean;
  hasDoor?: boolean;
  lightingType?: string;
  brightness?: number;
  colorTemperature?: number;
  includeToilet?: boolean;
  toiletStyle?: 'modern' | 'traditional' | 'wall-mounted';
  toiletPosition?: 'left' | 'right';
  includeShower?: boolean;
  showerStyle?: 'walk-in' | 'enclosed' | 'corner';
  includeBathtub?: boolean;
  bathtubStyle?: 'freestanding' | 'alcove' | 'corner';
  bathtubPosition?: 'left' | 'right' | 'back';
  wallFinishType?: 'paint' | 'tile';
  wallPaintColor?: string;
  wallTileColor?: string;
  includeMirror?: boolean;
  mirrorType?: 'mirror' | 'medicine-cabinet';
  mirrorSize?: 'small' | 'medium' | 'large';
  mirrorShape?: 'rectangular' | 'round' | 'oval' | 'arched';
  mirrorFrame?: 'none' | 'black' | 'chrome' | 'gold' | 'wood';
  includeTowelBar?: boolean;
  towelBarPosition?: 'left' | 'right' | 'center';
  includeToiletPaperHolder?: boolean;
  includeRobeHooks?: boolean;
  robeHookCount?: number;
  includeShelving?: boolean;
  shelvingType?: 'floating' | 'corner' | 'ladder';
  includeFaucet?: boolean;
  faucetStyle?: 'modern' | 'traditional' | 'waterfall';
  faucetFinish?: 'chrome' | 'brushed-nickel' | 'matte-black' | 'gold';
  countertopMaterial?: 'marble' | 'quartz' | 'granite';
  countertopEdge?: 'straight' | 'beveled' | 'bullnose' | 'waterfall';
  countertopColor?: string;
  sinkStyle?: 'undermount' | 'vessel' | 'integrated';
  sinkShape?: 'oval' | 'rectangular' | 'square';
  includeBacksplash?: boolean;
  backsplashMaterial?: 'subway-tile' | 'marble-slab' | 'glass-tile' | 'stone';
  backsplashHeight?: '4-inch' | 'full-height';
  includeVanityLighting?: boolean;
  vanityLightingStyle?: 'sconce' | 'led-strip' | 'pendant';
  vanityLightBrightness?: number;
  vanityLightTemp?: number;
}
