// AUTO-GENERATED by scripts/finishes/import-supplier.ts.
// Brands are discovered by scanning src/data/finishes/*.ts.
import type { MaterialBrand, MaterialPanel } from "@/types/materials";
import { AGT_PANELS, AGT_CATALOG_URL } from "./agt";
import { EGGER_PANELS, EGGER_CATALOG_URL } from "./egger";
import { WILSONART_PANELS, WILSONART_CATALOG_URL } from "./wilsonart";

export const ALL_PANELS: MaterialPanel[] = [
  ...AGT_PANELS,
  ...EGGER_PANELS,
  ...WILSONART_PANELS,
];

export const PANELS_BY_BRAND: Record<MaterialBrand, MaterialPanel[]> = {
  "AGT": AGT_PANELS,
  "Egger": EGGER_PANELS,
  "Wilsonart": WILSONART_PANELS,
};

export const BRAND_FULL_CATALOG_URL: Partial<Record<MaterialBrand, string>> = {
  "AGT": AGT_CATALOG_URL,
  "Egger": EGGER_CATALOG_URL,
  "Wilsonart": WILSONART_CATALOG_URL,
};
