// AUTO-GENERATED by scripts/finishes/import-supplier.ts.
// Brands are discovered by scanning src/data/finishes/*.ts.
import type { MaterialBrand, MaterialPanel } from "@/types/materials";
import { AGT_PANELS, AGT_CATALOG_URL } from "./agt";
import { EGGER_PANELS, EGGER_CATALOG_URL } from "./egger";
import { RAPHAEL_PANELS, RAPHAEL_CATALOG_URL } from "./raphael";
import { SHINNOKI_PANELS } from "./shinnoki";
import { TAFISA_PANELS } from "./tafisa";
import { WILSONART_PANELS, WILSONART_CATALOG_URL } from "./wilsonart";

export const ALL_PANELS: MaterialPanel[] = [
  ...AGT_PANELS,
  ...EGGER_PANELS,
  ...RAPHAEL_PANELS,
  ...SHINNOKI_PANELS,
  ...TAFISA_PANELS,
  ...WILSONART_PANELS,
];

export const PANELS_BY_BRAND: Record<MaterialBrand, MaterialPanel[]> = {
  "AGT": AGT_PANELS,
  "Egger": EGGER_PANELS,
  "Raphael Stone": RAPHAEL_PANELS,
  "Shinnoki": SHINNOKI_PANELS,
  "Tafisa": TAFISA_PANELS,
  "Wilsonart": WILSONART_PANELS,
};

export const BRAND_FULL_CATALOG_URL: Partial<Record<MaterialBrand, string>> = {
  "AGT": AGT_CATALOG_URL,
  "Egger": EGGER_CATALOG_URL,
  "Raphael Stone": RAPHAEL_CATALOG_URL,
  "Wilsonart": WILSONART_CATALOG_URL,
};
