/**
 * Image Import Replacement Script
 * 
 * This script automatically replaces local gallery image imports with CDN URLs
 * using the mapping file generated by migrate-gallery-images.ts
 * 
 * Usage: npx tsx scripts/replace-image-imports.ts
 */

import { readFile, writeFile, readdir } from 'fs/promises';
import { join, extname } from 'path';
import { existsSync } from 'fs';

const MAPPING_FILE = 'scripts/gallery-url-mapping.json';
const SOURCE_DIRS = ['src/components', 'src/pages', 'src/features'];

interface ImageMapping {
  originalPath: string;
  cdnUrl: string;
  filename: string;
  size: number;
  uploaded: boolean;
  error?: string;
}

interface Replacement {
  file: string;
  before: string;
  after: string;
  line: number;
}

/**
 * Load the image mapping file
 */
async function loadMapping(): Promise<Map<string, string>> {
  if (!existsSync(MAPPING_FILE)) {
    throw new Error(
      `Mapping file not found: ${MAPPING_FILE}\n` +
      'Please run migrate-gallery-images.ts first.'
    );
  }

  const content = await readFile(MAPPING_FILE, 'utf-8');
  const mappings: ImageMapping[] = JSON.parse(content);

  const map = new Map<string, string>();
  
  for (const mapping of mappings) {
    if (mapping.uploaded) {
      // Extract just the filename for matching
      const filename = mapping.filename;
      map.set(filename, mapping.cdnUrl);
    }
  }

  console.log(`📥 Loaded ${map.size} CDN URL mappings\n`);
  return map;
}

/**
 * Find all TypeScript/JavaScript files recursively
 */
async function findSourceFiles(dir: string): Promise<string[]> {
  const files: string[] = [];
  
  if (!existsSync(dir)) {
    return files;
  }

  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      // Recursively search subdirectories
      const subFiles = await findSourceFiles(fullPath);
      files.push(...subFiles);
    } else if (entry.isFile()) {
      // Include .ts, .tsx, .js, .jsx files
      const ext = extname(entry.name);
      if (['.ts', '.tsx', '.js', '.jsx'].includes(ext)) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

/**
 * Process a single file and find/replace image imports
 */
async function processFile(
  filePath: string,
  urlMap: Map<string, string>
): Promise<Replacement[]> {
  const content = await readFile(filePath, 'utf-8');
  const lines = content.split('\n');
  const replacements: Replacement[] = [];

  // Regex to match: import imageName from "@/assets/gallery/image-name.jpg"
  const importRegex = /import\s+(\w+)\s+from\s+["']@\/assets\/gallery\/([^"']+)["']/g;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    let match;

    while ((match = importRegex.exec(line)) !== null) {
      const varName = match[1];
      const filename = match[2];

      // Check if we have a CDN URL for this image
      if (urlMap.has(filename)) {
        const cdnUrl = urlMap.get(filename)!;
        
        // Create the replacement
        const before = match[0];
        const after = `const ${varName} = "${cdnUrl}";`;

        replacements.push({
          file: filePath,
          before,
          after,
          line: i + 1,
        });

        console.log(`  ${varName}: ${filename} → CDN`);
      }
    }
  }

  return replacements;
}

/**
 * Apply replacements to a file
 */
async function applyReplacements(
  filePath: string,
  replacements: Replacement[]
): Promise<void> {
  if (replacements.length === 0) return;

  let content = await readFile(filePath, 'utf-8');

  // Apply each replacement
  for (const replacement of replacements) {
    content = content.replace(replacement.before, replacement.after);
  }

  await writeFile(filePath, content, 'utf-8');
}

/**
 * Main replacement function
 */
async function replaceImageImports() {
  console.log('🔄 Starting image import replacement...\n');

  try {
    // Load the URL mapping
    const urlMap = await loadMapping();

    // Find all source files
    let allFiles: string[] = [];
    for (const dir of SOURCE_DIRS) {
      const files = await findSourceFiles(dir);
      allFiles = allFiles.concat(files);
    }

    console.log(`📂 Found ${allFiles.length} source files to scan\n`);

    // Process each file
    let totalReplacements = 0;
    const filesChanged: string[] = [];

    for (const file of allFiles) {
      const replacements = await processFile(file, urlMap);

      if (replacements.length > 0) {
        console.log(`\n📝 ${file}:`);
        await applyReplacements(file, replacements);
        totalReplacements += replacements.length;
        filesChanged.push(file);
      }
    }

    // Summary
    console.log('\n\n📊 Replacement Summary:');
    console.log(`   Total replacements: ${totalReplacements}`);
    console.log(`   Files changed: ${filesChanged.length}`);

    if (filesChanged.length > 0) {
      console.log('\n✅ Successfully updated files:');
      filesChanged.forEach((file) => console.log(`   - ${file}`));
    }

    console.log('\n✨ Import replacement complete!');
    console.log('\n⚠️  Please review the changes and test your application.');

  } catch (error) {
    console.error('❌ Replacement failed:', error);
    process.exit(1);
  }
}

// Run replacement
replaceImageImports().catch(console.error);
